name: incuse smoke

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: incuse-2vcpu-4gb-20gb-amd64
    steps:
      - name: Show host
        run: |
          uname -a
          cat /etc/os-release
          ip -4 addr show
          nproc
          free -m
      - name: Sleep
        run: sleep 5
      - name: Done
        run: echo done
